spring.application.name=Backend-MATE

# 1. MariaDB 접속 설정 (mate_db는 데이터베이스 방 이름)
spring.datasource.url=jdbc:mariadb://localhost:3306/mate_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
# 본인의 로컬 MariaDB 아이디
spring.datasource.username=root
# 본인의 로컬 MariaDB 비밀번호
spring.datasource.password=maria
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# 2. JPA 및 Hibernate 설정
# 우리가 짤 Entity 클래스 코드를 보고 DB 테이블을 자동으로 생성/수정해 주는 마법의 옵션!
spring.jpa.hibernate.ddl-auto=update
# 콘솔 창에 실행되는 SQL 쿼리문을 보여줌
spring.jpa.show-sql=true
# SQL 쿼리를 한 줄이 아니라 예쁘게 줄바꿈해서 보여줌
spring.jpa.properties.hibernate.format_sql=true
# MariaDB 전용 문법 사용
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect