# ==========================================
# 공통 애플리케이션 설정
# ==========================================
spring.application.name=Backend-MATE

# 기본적으로 활성화할 프로파일 (로컬 개발용인 dev로 설정)
spring.profiles.active=dev

# (참고) JWT 시크릿 키 등 모든 환경에서 공통으로 쓰이는 설정이 있다면 나중에 여기에 추가합니다.