# ==========================================
# In-Memory Database 설정 (H2)
# ==========================================
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:mate_test;MODE=MariaDB;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

# ==========================================
# JPA 및 Hibernate 설정
# ==========================================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# ==========================================
# 로깅 설정
# ==========================================
logging.level.root=INFO
logging.level.com.rookies5.Backend_MATE=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}:%line] - %msg%n
